### ISSUE TITLE
Archer

### ISSUE THREAD

**Issue by BuLuTBaYLaN** [HB2FT/Alp#165]
Okçunun geri tepmesi kapanacak
Ölünce 2 sn sonra yok olacak

**Comment by Haldun-Altuntop** [comment]
Öldükten sonra yok olması düzeltildi. (**V 0.14.10**)

**Comment by Haldun-Altuntop** [comment]
Okçunun geri tepmesi kapatıldı (**0.14.12**)
> Okçunun kodları değiştirilmedi. Playerın saldırı esnasında geri fırlatması devre dışı bırakıldı.
